name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  actions: read
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    uses: EsionHsrahLatigid/yup-actions/.github/workflows/plugin-release.yml@83c2b82cde8050bcb12acce1c24b2aa18da9f1bd
    with:
      product_name: BlackThrum
